---
# Source: argo-cd/templates/argocd-configs/argocd-cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    helm.sh/chart: argo-cd-3.35.4
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/component: server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
data:
    application.instanceLabelKey: argocd.argoproj.io/instance
    dex.config: |
      logger:
        level: error
        format: json
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: $dex.github.client.id
            clientSecret: $dex.github.client.secret
            orgs:
              - name: $dex.github.organization
    resource.compareoptions: |
      ignoreResourceStatusField: all
    resource.customizations.health.cert-manager.io_Certificate: |
      hs = {}
      if obj.status ~= nil then
        if obj.status.conditions ~= nil then
          for i, condition in ipairs(obj.status.conditions) do
            if condition.type == "Ready" and condition.status == "False" then
              hs.status = "Degraded"
              hs.message = condition.message
              return hs
            end
            if condition.type == "Ready" and condition.status == "True" then
              hs.status = "Healthy"
              hs.message = condition.message
              return hs
            end
          end
        end
      end
      hs.status = "Progressing"
      hs.message = "Waiting for certificate"
      return hs
    resource.customizations.ignoreDifferences.admissionregistration.k8s.io_MutatingWebhookConfiguration: |
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
    url: https://argocd.homelab.monetact.net
