---
# Source: argo-cd/templates/argocd-configs/argocd-rbac-cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  labels:
    helm.sh/chart: argo-cd-3.35.4
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/component: server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
data:
    policy.csv: |
      p, role:readonly-limited, applications, get, */*, allow
      p, role:readonly-limited, projects, get, *, allow
      p, role:readonly-limited, clusters, get, *, allow
    
      p, role:sync, applications, sync, */*, allow
    
      p, role:application-admin, applications, *, */*, allow
      p, role:account-admin, accounts, *, *, allow
    
      g, role:sync, role:readonly
      g, role:application:admin, role:readonly
      g, role:account-admin, role:readonly
      g, moopholo:family, role:admin
    policy.default: role:readonly-limited
