---
# Source: argo-cd/templates/redis/metrics-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: argocd-redis-metrics
  annotations:
    prometheus.io/scrape: "true"
  labels:
    helm.sh/chart: argo-cd-3.35.4
    app.kubernetes.io/name: argocd-redis
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/component: redis
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      protocol: TCP
      port: 9121
      targetPort: metrics
  selector:
    app.kubernetes.io/name: argocd-redis
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/component: redis
  type: ClusterIP
