---
# Source: grafana/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  namespace: grafana
  labels:
    helm.sh/chart: grafana-6.61.2
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/version: "10.1.5"
    app.kubernetes.io/managed-by: Helm
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [auth.github]
    allow_sign_up = true
    allowed_organizations = moopholo
    api_url = https://api.github.com/user
    auth_url = https://github.com/login/oauth/authorize
    client_id = 
    client_secret = 
    enabled = true
    scopes = user:email,read:org
    team_ids = 5230329
    token_url = https://github.com/login/oauth/access_token
    [grafana_net]
    url = https://grafana.com
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [security]
    disable_initial_admin_creation = true
    [server]
    domain = grafana.homelab.monetact.net
    enable_gzip = true
    root_url = https://%(domain)s
    [users]
    auto_assign_org_role = Editor
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      isDefault: true
      name: Prometheus
      type: prometheus
      url: http://prometheus-server.prometheus
  download_dashboards.sh: |
    #!/usr/bin/env sh
    set -euf
  
    curl -skf \
    --connect-timeout 60 \
    --max-time 60 \
    -H "Accept: application/json" \
    -H "Content-Type: application/json;charset=UTF-8" \
      "https://grafana.com/api/dashboards/2842/revisions/1/download" \
      | sed '/-- .* --/! s/"datasource":.*,/"datasource": "Prometheus",/g' \
    > "/var/lib/grafana/dashboards/default/ceph-cluster.json"
      
    curl -skf \
    --connect-timeout 60 \
    --max-time 60 \
    -H "Accept: application/json" \
    -H "Content-Type: application/json;charset=UTF-8" \
      "https://grafana.com/api/dashboards/5336/revisions/1/download" \
      | sed '/-- .* --/! s/"datasource":.*,/"datasource": "Prometheus",/g' \
    > "/var/lib/grafana/dashboards/default/ceph-osd.json"
      
    curl -skf \
    --connect-timeout 60 \
    --max-time 60 \
    -H "Accept: application/json" \
    -H "Content-Type: application/json;charset=UTF-8" \
      "https://grafana.com/api/dashboards/5342/revisions/1/download" \
      | sed '/-- .* --/! s/"datasource":.*,/"datasource": "Prometheus",/g' \
    > "/var/lib/grafana/dashboards/default/ceph-pools.json"
