---
# Source: argocd-applicationset/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-applicationset
  labels:
    helm.sh/chart: argocd-applicationset-1.12.1
    app.kubernetes.io/name: argocd-applicationset
    app.kubernetes.io/instance: argocd-applicationset
    app.kubernetes.io/version: "v0.4.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argo-cd-applicationset
    app.kubernetes.io/component: controller
